language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version used by your project
    - build-tools-26.0.0

    # The SDK version used to compile your project
    - android-26

    # Additional components
    # - extra-android-m2repository


before_install:
  - chmod +x gradlew

  # workaround for "http://stackoverflow.com/questions/37615379/travis-ci-build-doesnt-work-with-android-constraint-layout"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew build